name: Auto Commit and Push

on:
  schedule:
    - cron: '*/3 * * * *' # Set the schedule to run every 3 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3  # Specify your Python version

      - name: Install dependencies
        run: pip install pytz  # Modify this as needed

      - name: Run your script
        run: python main.py  # Replace with the actual command to run your script

      - name: Commit and Push changes
        run: |
          git config user.name "ujjwal-dhiman-ai"
          git config user.email "ukdhiman11@gmail.com"
          git remote set-url origin https://$GH_PAT@github.com/ujjwal-dhiman-ai/test-actions.git
          git add .
          git commit -m "Auto commit by GitHub Actions"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      
